<a href="https://colab.research.google.com/github/mariumnour/Project-1/blob/main/Thesis2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Datasets/

/content/drive/MyDrive/Datasets

In [3]:
# IDS 2018 Intrusion CSVs (CSE-CIC-IDS2018)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#dtypes = {'Protocol' : str ,'Flow Duration' : str ,'Tot Fwd Pkts' : str ,'Tot Bwd Pkts' : str ,'TotLen Fwd Pkts' : str}
#df = pd.read_csv('03-01-2018.csv', dtype=dtypes)
df = pd.read_csv('03-01-2018.csv')
df.head()

<ipython-input-3-e0c2f4e5f1ef>:8: DtypeWarning: Columns (0,1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('03-01-2018.csv')

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,0,0,01/03/2018 08:17:11,115307855,5,0,0,0,0,0,...,0,1812348,0,1812348,1812348,56700000,6010057.622,61000000,52500000,Benign
1,0,0,01/03/2018 08:20:07,60997457,2,0,0,0,0,0,...,0,0,0,0,0,61000000,0,61000000,61000000,Benign
2,67,17,01/03/2018 08:17:18,61149019,5,0,1500,0,300,300,...,8,3530939,0,3530939,3530939,19200000,12500000,32600000,7999725,Benign
3,0,0,01/03/2018 08:22:09,60997555,2,0,0,0,0,0,...,0,0,0,0,0,61000000,0,61000000,61000000,Benign
4,0,0,01/03/2018 08:24:11,61997503,3,0,0,0,0,0,...,0,999909,0,999909,999909,61000000,0,61000000,61000000,Benign

In [4]:
df = pd.read_csv('03-01-2018.csv', low_memory=False)

In [5]:
print(df.dtypes)

Dst Port         object
Protocol         object
Timestamp        object
Flow Duration    object
Tot Fwd Pkts     object
                  ...
Idle Mean        object
Idle Std         object
Idle Max         object
Idle Min         object
Label            object
Length: 80, dtype: object

In [6]:
#print(df['Dst Port'].unique())
df['Dst Port'] = df['Dst Port'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Dst Port'] = df['Dst Port'].astype(str).astype(int)

#print(df['Flow Duration'].unique())
df['Flow Duration'] = df['Dst Port'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow Duration'] = df['Flow Duration'].astype(int)

#print(df['Tot Fwd Pkts'].unique())
df['Tot Fwd Pkts'] = df['Tot Fwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Tot Fwd Pkts'] = df['Tot Fwd Pkts'].astype(int)


#print(df['Tot Bwd Pkts'].unique())
df['Tot Bwd Pkts'] = df['Tot Bwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Tot Bwd Pkts'] = df['Tot Bwd Pkts'].astype(int)

#print(df['TotLen Fwd Pkts'].unique())
df['TotLen Fwd Pkts'] = df['TotLen Fwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['TotLen Fwd Pkts'] = df['TotLen Fwd Pkts'].astype(int)

#print(df['TotLen Bwd Pkts'].unique())
df['TotLen Bwd Pkts'] = df['TotLen Bwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['TotLen Bwd Pkts'] = df['TotLen Bwd Pkts'].astype(int)

#print(df['Fwd Pkt Len Max'].unique())
df['Fwd Pkt Len Max'] = df['Fwd Pkt Len Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkt Len Max'] = df['Fwd Pkt Len Max'].astype(int)

#print(df['Fwd Pkt Len Min'].unique())
df['Fwd Pkt Len Min'] = df['Fwd Pkt Len Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkt Len Min'] = df['Fwd Pkt Len Min'].astype(int)

#print(df['Fwd Pkt Len Mean'].unique())
df['Fwd Pkt Len Mean'] = df['Fwd Pkt Len Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkt Len Mean'] = df['Fwd Pkt Len Mean'].astype(float)


#print(df['Fwd Pkt Len Std'].unique())
df['Fwd Pkt Len Std'] = df['Fwd Pkt Len Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkt Len Std'] = df['Fwd Pkt Len Std'].astype(float)

#print(df['Bwd Pkt Len Max'].unique())
df['Bwd Pkt Len Max'] = df['Bwd Pkt Len Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Pkt Len Max'] = df['Bwd Pkt Len Max'].astype(int)

#print(df['Bwd Pkt Len Min'].unique())
df['Bwd Pkt Len Min'] = df['Bwd Pkt Len Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Pkt Len Min'] = df['Bwd Pkt Len Min'].astype(int)

#print(df['Bwd Pkt Len Mean'].unique())
df['Bwd Pkt Len Mean'] = df['Bwd Pkt Len Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Pkt Len Mean'] = df['Bwd Pkt Len Mean'].astype(float)

#print(df['Bwd Pkt Len Std'].unique())
df['Bwd Pkt Len Std'] = df['Bwd Pkt Len Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Pkt Len Std'] = df['Bwd Pkt Len Std'].astype(float)

#print(df['Flow Byts/s'].unique())
df['Flow Byts/s'] = df['Flow Byts/s'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow Byts/s'] = df['Flow Byts/s'].astype(float)

#print(df['Flow Pkts/s'].unique())
df['Flow Pkts/s'] = df['Flow Pkts/s'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow Pkts/s'] = df['Flow Pkts/s'].astype(float)

#print(df['Flow IAT Mean'].unique())
df['Flow IAT Mean'] = pd.to_numeric(df['Flow IAT Mean'], errors='coerce')
df['FFlow IAT Mean'] = df['Flow IAT Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow IAT Mean'] = df['Flow IAT Mean'].astype(float)

#print(df['Flow IAT Std'].unique())
df['Flow IAT Std'] = df['Flow IAT Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow IAT Std'] = df['Flow IAT Std'].astype(float)

#print(df['Flow IAT Max'].unique())
df['Flow IAT Max'] = df['Flow IAT Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow IAT Max'] = df['Flow IAT Max'].astype(int)

#print(df['Flow IAT Min'].unique())
df['Flow IAT Min'] = df['Flow IAT Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Flow IAT Min'] = df['Flow IAT Min'].astype(int)

#print(df['Fwd IAT Tot'].unique())
df['Fwd IAT Tot'] = df['Fwd IAT Tot'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd IAT Tot'] = df['Fwd IAT Tot'].astype(int)

#print(df['Fwd IAT Mean'].unique())
df['Fwd IAT Mean'] = df['Fwd IAT Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd IAT Mean'] = df['Fwd IAT Mean'].astype(float)

#print(df['Fwd IAT Std'].unique())
df['Fwd IAT Std'] = df['Fwd IAT Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd IAT Std'] = df['Fwd IAT Std'].astype(float)

#print(df['Flow IAT Max'].unique())
df['Fwd IAT Max'] = df['Flow IAT Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd IAT Max'] = df['Fwd IAT Max'].astype(int)

#df['Flow IAT Max'] = df['Flow IAT Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
#print(df['Fwd IAT Min'].unique())
# Replace any non-integer values with NaN
df['Fwd IAT Min'] = pd.to_numeric(df['Fwd IAT Min'], errors='coerce')
# Convert the 'Fwd IAT Min' column to integers, and set NaN values to -1
df['Fwd IAT Min'] = df['Fwd IAT Min'].fillna(-1).astype(int)
df['Fwd IAT Min'] = df['Fwd IAT Min'].astype(int)

#print(df['Bwd IAT Tot'].unique())
df['Bwd IAT Tot'] = df['Bwd IAT Tot'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd IAT Tot'] = df['Bwd IAT Tot'].astype(int)

#print(df['Bwd IAT Mean'].unique())
df['Bwd IAT Mean'] = df['Bwd IAT Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd IAT Mean'] = df['Bwd IAT Mean'].astype(float)

#print(df['Bwd IAT Std'].unique())
df['Bwd IAT Std'] = df['Bwd IAT Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd IAT Std'] = df['Bwd IAT Std'].astype(float)

#print(df['Bwd IAT Max'].unique())
df['Bwd IAT Max'] = df['Bwd IAT Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd IAT Max'] = df['Bwd IAT Max'].astype(int)

#print(df['Bwd IAT Min'].unique())
df['Bwd IAT Min'] = df['Bwd IAT Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd IAT Min'] = df['Bwd IAT Min'].astype(int)

#print(df['Fwd PSH Flags'].unique())
df['Fwd PSH Flags'] = df['Fwd PSH Flags'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd PSH Flags'] = df['Fwd PSH Flags'].astype(int)

#print(df['Bwd PSH Flags'].unique())
df['Bwd PSH Flags'] = df['Bwd PSH Flags'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd PSH Flags'] = df['Bwd PSH Flags'].astype(int)

#print(df['Fwd URG Flags'].unique())
df['Fwd URG Flags'] = df['Fwd URG Flags'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd URG Flags'] = df['Fwd URG Flags'].astype(int)

#print(df['Bwd URG Flags'].unique())
df['Bwd URG Flags'] = df['Bwd URG Flags'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd URG Flags'] = df['Bwd URG Flags'].astype(int)

#print(df['Fwd Header Len'].unique())
df['Fwd Header Len'] = df['Fwd Header Len'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Header Len'] = df['Fwd Header Len'].astype(int)

#print(df['Bwd Header Len'].unique())
df['Bwd Header Len'] = df['Bwd Header Len'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Header Len'] = df['Bwd Header Len'].astype(int)

#print(df['Fwd Pkts/s'].unique())
df['Fwd Pkts/s'] = df['Fwd Pkts/s'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkts/s'] = df['Fwd Pkts/s'].astype(float)

#print(df['Bwd Pkts/s'].unique())
df['Bwd Pkts/s'] = df['Bwd Pkts/s'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Pkts/s'] = df['Bwd Pkts/s'].astype(float)

#print(df['Pkt Len Min'].unique())
df['Pkt Len Min'] = df['Pkt Len Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Len Min'] = df['Pkt Len Min'].astype(int)

#print(df['Pkt Len Max'].unique())
df['Pkt Len Max'] = df['Pkt Len Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Len Max'] = df['Pkt Len Max'].astype(int)

#print(df['Pkt Len Mean'].unique())
df['Pkt Len Mean'] = df['Pkt Len Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Len Mean'] = df['Pkt Len Mean'].astype(float)

#print(df['Pkt Len Std'].unique())
df['Pkt Len Std'] = df['Pkt Len Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Len Std'] = df['Pkt Len Std'].astype(float)

#print(df['Pkt Len Var'].unique())
df['Pkt Len Var'] = df['Pkt Len Var'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Len Var'] = df['Pkt Len Var'].astype(float)

#print(df['FIN Flag Cnt'].unique())
df['FIN Flag Cnt'] = df['FIN Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['FIN Flag Cnt'] = df['FIN Flag Cnt'].astype(int)

#print(df['SYN Flag Cnt'].unique())
df['SYN Flag Cnt'] = df['SYN Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['SYN Flag Cnt'] = df['SYN Flag Cnt'].astype(int)

#print(df['RST Flag Cnt'].unique())
df['RST Flag Cnt'] = df['RST Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['RST Flag Cnt'] = df['RST Flag Cnt'].astype(int)

#print(df['PSH Flag Cnt'].unique())
df['PSH Flag Cnt'] = df['PSH Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['PSH Flag Cnt'] = df['PSH Flag Cnt'].astype(int)

#print(df['ACK Flag Cnt'].unique())
df['ACK Flag Cnt'] = df['ACK Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['ACK Flag Cnt'] = df['ACK Flag Cnt'].astype(int)

#print(df['URG Flag Cnt'].unique())
df['URG Flag Cnt'] = df['URG Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['URG Flag Cnt'] = df['URG Flag Cnt'].astype(int)

#print(df['CWE Flag Count'].unique())
df['CWE Flag Count'] = df['CWE Flag Count'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['CWE Flag Count'] = df['CWE Flag Count'].astype(int)

#print(df['ECE Flag Cnt'].unique())
df['ECE Flag Cnt'] = df['ECE Flag Cnt'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['ECE Flag Cnt'] = df['ECE Flag Cnt'].astype(int)

#print(df['Down/Up Ratio'].unique())
df['Down/Up Ratio'] = df['Down/Up Ratio'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Down/Up Ratio'] = df['Down/Up Ratio'].astype(int)

#print(df['Pkt Size Avg'].unique())
df['Pkt Size Avg'] = df['Pkt Size Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Pkt Size Avg'] = df['Pkt Size Avg'].astype(float)

#print(df['Fwd Seg Size Avg'].unique())
df['Fwd Seg Size Avg'] = df['Fwd Seg Size Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Seg Size Avg'] = df['Fwd Seg Size Avg'].astype(float)

#print(df['Bwd Seg Size Avg'].unique())
df['Bwd Seg Size Avg'] = df['Bwd Seg Size Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Seg Size Avg'] = df['Bwd Seg Size Avg'].astype(float)

#print(df['Fwd Byts/b Avg'].unique())
df['Fwd Byts/b Avg'] = df['Fwd Byts/b Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Byts/b Avg'] = df['Fwd Byts/b Avg'].astype(int)

#print(df['Fwd Pkts/b Avg'].unique())
df['Fwd Pkts/b Avg'] = df['Fwd Pkts/b Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Pkts/b Avg'] = df['Fwd Pkts/b Avg'].astype(int)

#print(df['Fwd Blk Rate Avg'].unique())
df['Fwd Blk Rate Avg'] = df['Fwd Blk Rate Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Blk Rate Avg'] = df['Fwd Blk Rate Avg'].astype(int)

#print(df['Bwd Byts/b Avg'].unique())
df['Bwd Byts/b Avg'] = df['Bwd Byts/b Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Byts/b Avg'] = df['Bwd Byts/b Avg'].astype(int)

#print(df['Bwd Blk Rate Avg'].unique())
df['Bwd Blk Rate Avg'] = df['Bwd Blk Rate Avg'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Bwd Blk Rate Avg'] = df['Bwd Blk Rate Avg'].astype(int)

#print(df['Subflow Fwd Pkts'].unique())
df['Subflow Fwd Pkts'] = df['Subflow Fwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Subflow Fwd Pkts'] = df['Subflow Fwd Pkts'].astype(int)

#print(df['Subflow Fwd Byts'].unique())
df['Subflow Fwd Byts'] = df['Subflow Fwd Byts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Subflow Fwd Byts'] = df['Subflow Fwd Byts'].astype(int)

#print(df['Subflow Bwd Pkts'].unique())
df['Subflow Bwd Pkts'] = df['Subflow Bwd Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Subflow Bwd Pkts'] = df['Subflow Bwd Pkts'].astype(int)

#print(df['Subflow Bwd Byts'].unique())
df['Subflow Bwd Byts'] = df['Subflow Bwd Byts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Subflow Bwd Byts'] = df['Subflow Bwd Byts'].astype(int)

#print(df['Init Fwd Win Byts'].unique())
df['Init Fwd Win Byts'] = df['Init Fwd Win Byts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Init Fwd Win Byts'] = df['Init Fwd Win Byts'].astype(int)

#print(df['Init Bwd Win Byts'].unique())
df['Init Bwd Win Byts'] = df['Init Bwd Win Byts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Init Bwd Win Byts'] = df['Init Bwd Win Byts'].astype(int)

#print(df['Fwd Act Data Pkts'].unique())
df['Fwd Act Data Pkts'] = df['Fwd Act Data Pkts'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Act Data Pkts'] = df['Fwd Act Data Pkts'].astype(int)

#print(df['Fwd Seg Size Min'].unique())
df['Fwd Seg Size Min'] = df['Fwd Seg Size Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Fwd Seg Size Min'] = df['Fwd Seg Size Min'].astype(int)

#print(df['Active Mean'].unique())
df['Active Mean'] = df['Active Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Active Mean'] = df['Active Mean'].astype(float)

#print(df['Active Std'].unique())
df['Active Std'] = df['Active Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Active Std'] = df['Active Std'].astype(float)

#print(df['Active Max'].unique())
df['Active Max'] = df['Active Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Active Max'] = df['Active Max'].astype(int)

#print(df['Active Min'].unique())
df['Active Min'] = df['Active Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Active Min'] = df['Active Min'].astype(int)

#print(df['Idle Mean'].unique())
df['Idle Mean'] = df['Idle Mean'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Idle Mean'] = df['Idle Mean'].astype(float)

#print(df['Idle Std'].unique())
df['Idle Std'] = df['Idle Std'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Idle Std'] = df['Idle Std'].astype(float)

#print(df['Idle Max'].unique())
df['Idle Max'] = df['Idle Max'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Idle Max'] = df['Idle Max'].astype(int)

#print(df['Idle Min'].unique())
df['Idle Min'] = df['Idle Min'].apply(lambda x: int(x) if str(x).isdigit() else -1)
df['Idle Min'] = df['Idle Min'].astype(int)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 331125 entries, 0 to 331124
Data columns (total 81 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Dst Port           331125 non-null  int64
 1   Protocol           331125 non-null  object
 2   Timestamp          331125 non-null  object
 3   Flow Duration      331125 non-null  int64
 4   Tot Fwd Pkts       331125 non-null  int64
 5   Tot Bwd Pkts       331125 non-null  int64
 6   TotLen Fwd Pkts    331125 non-null  int64
 7   TotLen Bwd Pkts    331125 non-null  int64
 8   Fwd Pkt Len Max    331125 non-null  int64
 9   Fwd Pkt Len Min    331125 non-null  int64
 10  Fwd Pkt Len Mean   331125 non-null  float64
 11  Fwd Pkt Len Std    331125 non-null  float64
 12  Bwd Pkt Len Max    331125 non-null  int64
 13  Bwd Pkt Len Min    331125 non-null  int64
 14  Bwd Pkt Len Mean   331125 non-null  float64
 15  Bwd Pkt Len Std    331125 non-null  float64
 16  Flow Byts/s        331125 non-null  float64
 17  Flow Pkts/s        331125 non-null  float64
 18  Flow IAT Mean      331100 non-null  float64
 19  Flow IAT Std       331125 non-null  float64
 20  Flow IAT Max       331125 non-null  int64
 21  Flow IAT Min       331125 non-null  int64
 22  Fwd IAT Tot        331125 non-null  int64
 23  Fwd IAT Mean       331125 non-null  float64
 24  Fwd IAT Std        331125 non-null  float64
 25  Fwd IAT Max        331125 non-null  int64
 26  Fwd IAT Min        331125 non-null  int64
 27  Bwd IAT Tot        331125 non-null  int64
 28  Bwd IAT Mean       331125 non-null  float64
 29  Bwd IAT Std        331125 non-null  float64
 30  Bwd IAT Max        331125 non-null  int64
 31  Bwd IAT Min        331125 non-null  int64
 32  Fwd PSH Flags      331125 non-null  int64
 33  Bwd PSH Flags      331125 non-null  int64
 34  Fwd URG Flags      331125 non-null  int64
 35  Bwd URG Flags      331125 non-null  int64
 36  Fwd Header Len     331125 non-null  int64
 37  Bwd Header Len     331125 non-null  int64
 38  Fwd Pkts/s         331125 non-null  float64
 39  Bwd Pkts/s         331125 non-null  float64
 40  Pkt Len Min        331125 non-null  int64
 41  Pkt Len Max        331125 non-null  int64
 42  Pkt Len Mean       331125 non-null  float64
 43  Pkt Len Std        331125 non-null  float64
 44  Pkt Len Var        331125 non-null  float64
 45  FIN Flag Cnt       331125 non-null  int64
 46  SYN Flag Cnt       331125 non-null  int64
 47  RST Flag Cnt       331125 non-null  int64
 48  PSH Flag Cnt       331125 non-null  int64
 49  ACK Flag Cnt       331125 non-null  int64
 50  URG Flag Cnt       331125 non-null  int64
 51  CWE Flag Count     331125 non-null  int64
 52  ECE Flag Cnt       331125 non-null  int64
 53  Down/Up Ratio      331125 non-null  int64
 54  Pkt Size Avg       331125 non-null  float64
 55  Fwd Seg Size Avg   331125 non-null  float64
 56  Bwd Seg Size Avg   331125 non-null  float64
 57  Fwd Byts/b Avg     331125 non-null  int64
 58  Fwd Pkts/b Avg     331125 non-null  int64
 59  Fwd Blk Rate Avg   331125 non-null  int64
 60  Bwd Byts/b Avg     331125 non-null  int64
 61  Bwd Pkts/b Avg     331125 non-null  object
 62  Bwd Blk Rate Avg   331125 non-null  int64
 63  Subflow Fwd Pkts   331125 non-null  int64
 64  Subflow Fwd Byts   331125 non-null  int64
 65  Subflow Bwd Pkts   331125 non-null  int64
 66  Subflow Bwd Byts   331125 non-null  int64
 67  Init Fwd Win Byts  331125 non-null  int64
 68  Init Bwd Win Byts  331125 non-null  int64
 69  Fwd Act Data Pkts  331125 non-null  int64
 70  Fwd Seg Size Min   331125 non-null  int64
 71  Active Mean        331125 non-null  float64
 72  Active Std         331125 non-null  float64
 73  Active Max         331125 non-null  int64
 74  Active Min         331125 non-null  int64
 75  Idle Mean          331125 non-null  float64
 76  Idle Std           331125 non-null  float64
 77  Idle Max           331125 non-null  int64
 78  Idle Min           331125 non-null  int64
 79  Label              331125 non-null  object
 80  FFlow IAT Mean     331125 non-null  int64
dtypes: float64(24), int64(53), object(4)
memory usage: 204.6+ MB

In [8]:
#df['Flow Duration'] = pd.to_numeric(df['Flow Duration'], errors='coerce')

In [9]:
print(df.isnull().sum())

Dst Port          0
Protocol          0
Timestamp         0
Flow Duration     0
Tot Fwd Pkts      0
                 ..
Idle Std          0
Idle Max          0
Idle Min          0
Label             0
FFlow IAT Mean    0
Length: 81, dtype: int64

In [10]:
#df['Flow Byts/s'] = pd.to_numeric(df['Flow Byts/s'], errors='coerce')
df['Flow Byts/s'].fillna(df['Flow Byts/s'].mean(), inplace=True)

In [11]:
#df['Flow Pkts/s'] = pd.to_numeric(df['Flow Pkts/s'], errors='coerce')
df['Flow Pkts/s'].fillna(df['Flow Pkts/s'].mean(), inplace=True)

In [12]:
#df['Bwd IAT Tot'] = pd.to_numeric(df['Bwd IAT Tot'], errors='coerce')
df['Bwd IAT Tot'].fillna(df['Bwd IAT Tot'].mean(), inplace=True)

In [13]:
#df['Bwd IAT Max'] = pd.to_numeric(df['Bwd IAT Max'], errors='coerce')
df['Bwd IAT Max'].fillna(df['Bwd IAT Max'].mean(), inplace=True)

In [14]:
#Takes a random sample of 10% of the rows from the original DataFrame
sampled_data = df.sample(frac=0.10, random_state=2)

In [15]:
#counts the number of occurrences of each unique value in the "Label" column
sampled_data["Label"].value_counts()

Benign           23718
Infilteration     9389
Label                5
Name: Label, dtype: int64

In [16]:
#replaces all occurrences of the string "Bot" with the string "Malicious",
sampled_data.replace(to_replace=["Bot"], value="Malicious", inplace=True)

In [17]:
#!pip install --upgrade scikit-learn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import joblib
import sklearn
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
#from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, plot_confusion_matrix
from sklearn.utils import class_weight

In [18]:
# replace +ve and -ve infinity with NaN
sampled_data.replace([np.inf, -np.inf], np.nan, inplace=True)

# drop missing values
sampled_data.dropna(inplace=True)

In [19]:
train, test = train_test_split(sampled_data, test_size=0.3)

In [22]:
print(train.columns)

Index(['Dst Port', 'Protocol', 'Timestamp', 'Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min', 'Label',
       'FFlow IAT Mean'],
      dtype='object')

In [21]:
# Prepares for SVM and KNN
min_max_scaler = MinMaxScaler().fit(train[['Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min']])

In [20]:
numerical_columns = ['Flow Duration', 'Tot Fwd Pkts',
       'Tot Bwd Pkts', 'TotLen Fwd Pkts', 'TotLen Bwd Pkts', 'Fwd Pkt Len Max',
       'Fwd Pkt Len Min', 'Fwd Pkt Len Mean', 'Fwd Pkt Len Std',
       'Bwd Pkt Len Max', 'Bwd Pkt Len Min', 'Bwd Pkt Len Mean',
       'Bwd Pkt Len Std', 'Flow Byts/s', 'Flow Pkts/s', 'Flow IAT Mean',
       'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min', 'Fwd IAT Tot',
       'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max', 'Fwd IAT Min',
       'Bwd IAT Tot', 'Bwd IAT Mean', 'Bwd IAT Std', 'Bwd IAT Max',
       'Bwd IAT Min', 'Fwd PSH Flags', 'Bwd PSH Flags', 'Fwd URG Flags',
       'Bwd URG Flags', 'Fwd Header Len', 'Bwd Header Len', 'Fwd Pkts/s',
       'Bwd Pkts/s', 'Pkt Len Min', 'Pkt Len Max', 'Pkt Len Mean',
       'Pkt Len Std', 'Pkt Len Var', 'FIN Flag Cnt', 'SYN Flag Cnt',
       'RST Flag Cnt', 'PSH Flag Cnt', 'ACK Flag Cnt', 'URG Flag Cnt',
       'CWE Flag Count', 'ECE Flag Cnt', 'Down/Up Ratio', 'Pkt Size Avg',
       'Fwd Seg Size Avg', 'Bwd Seg Size Avg', 'Fwd Byts/b Avg',
       'Fwd Pkts/b Avg', 'Fwd Blk Rate Avg', 'Bwd Byts/b Avg',
       'Bwd Pkts/b Avg', 'Bwd Blk Rate Avg', 'Subflow Fwd Pkts',
       'Subflow Fwd Byts', 'Subflow Bwd Pkts', 'Subflow Bwd Byts',
       'Init Fwd Win Byts', 'Init Bwd Win Byts', 'Fwd Act Data Pkts',
       'Fwd Seg Size Min', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min']

In [23]:
train[numerical_columns] = min_max_scaler.transform(train[numerical_columns])

In [24]:
train

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label,FFlow IAT Mean
50820,53,17,01/03/2018 11:52:11,0.000809,0.000000,0.000038,0.000051,0.000004,0.020325,0.030864,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
56378,50653,6,01/03/2018 09:17:17,0.773080,0.000000,0.000038,0.000000,0.000000,0.000000,0.000000,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
241443,53,17,01/03/2018 09:28:37,0.000809,0.000000,0.000038,0.000042,0.000003,0.016768,0.025463,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
270980,0,0,01/03/2018 10:23:56,0.000000,0.005026,0.000000,0.000000,0.000000,0.000000,0.000000,...,4.095238e-01,1.000000e+00,0.774286,0.044935,1.136752e-01,0.000000e+00,0.117949,0.109402,Infilteration,-1
98584,33846,6,01/03/2018 01:13:32,0.516567,0.000077,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.523809e-09,1.848429e-08,0.000000,0.000000,7.384615e-01,2.631579e-08,0.738462,0.738462,Benign,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183756,53,17,01/03/2018 04:00:49,0.000809,0.000000,0.000038,0.000051,0.000004,0.020325,0.030864,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
329370,0,0,01/03/2018 12:50:44,0.000000,0.000155,0.000000,0.000000,0.000000,0.000000,0.000000,...,9.523809e-09,1.848429e-08,0.000000,0.000000,4.811966e-01,0.000000e+00,0.481197,0.481197,Benign,-1
254865,53,17,01/03/2018 09:56:11,0.000809,0.000000,0.000038,0.000047,0.000006,0.018801,0.028549,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
14494,53,17,01/03/2018 09:35:50,0.000809,0.000000,0.000038,0.000051,0.000004,0.020325,0.030864,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1
80278,5560,6,01/03/2018 10:24:45,0.084858,0.000000,0.000038,0.000000,0.000000,0.000000,0.000000,...,9.523809e-09,1.848429e-08,0.000000,0.000000,8.547008e-09,2.631579e-08,0.000000,0.000000,Benign,-1